#!/bin/bash

# Copyright (C) 2018 G.P. Halkes
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ "$(cat .git/HEAD)" == "ref: refs/heads/$1" ]] ; then
	echo "Can not close branch you are currently on"
	exit 1
fi
if [[ ! -f .git/refs/heads/$1 ]] ; then
	echo "Branch $1 does not exist"
	exit 1
fi
git tag "closed-branch/$1" "$1" || exit 1
git branch -D "$1" || git tag -d "closed-branch/$1"
