#!/bin/bash

# Copyright (C) 2018 G.P. Halkes
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ $# -gt 2 ]] || [[ $# -eq 0 ]] ; then echo
	echo "Usage: git setup-remote <name> [<URL>]" >&2
	exit 1
fi

if [[ $# -eq 1 ]] ; then
	if ! git config --get "remote.$1.url" > /dev/null ; then
		echo "No URL set for remote $1 and no URL supplied. Aborting." >&2
		exit 1
	fi
else
	git config "remote.$1.url" "$2"
fi

git config "remote.$1.fetch" "+refs/heads/*:refs/remotes/$1/*"
git config --replace-all "remote.$1.push" "refs/heads/*:refs/heads/*"
git config --add "remote.$1.push" "refs/tags/*:refs/tags/*"
